### ISSUE TITLE
Add Cutting Patterns to DB

### ISSUE THREAD

**Issue by wederbn** [PatternAtlas/pattern-atlas-content#28]

**Comment by salmma** [comment]
@mar-be please add patterns to DB until Friday, 3rd November 2023

**Comment by mar-be** [comment]
PR https://github.com/PatternAtlas/pattern-atlas-content/pull/31 adds cutting patterns with names, icons, and relationships to the DB. The remaining content will be added after the copyright is clarified.

**Comment by wederbn** [comment]
Closed by #31
